# Site settings
baseurl = "https://henriqueholanda.dev/"
themesDir = "./themes"
languageCode = "en-us"
title = "Henrique Holanda - Backend Developer"
theme = "hugo-cactus-theme"

googleAnalytics = "UA-114302825-2"
disqusShortname = "henriqueholanda" # Comment out to disable Disqus.

[params]
	name = "Henrique Holanda"
	description = ""
	bio = "Backend Developer"
	# Enter optionally your twitter account
	twitter = "henriqueholanda"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Backend Developer"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/henriqueholanda"
    github   = "https://www.github.com/henriqueholanda"
	email = "mailto:contato@henriqueholanda.com.br"